config/routes.rb
Rails.application.routes.draw do
  resources :notes
  root 'homes#top'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    def index
      @notes = Note.all
    end

    def new
      @note = Note.new
    end

    def show 
      @note = Note.find(params[:id])
    end
    
    def create 
      @note = Note.new(note_params)
      if @note.save
        redirect_to notes_path
      else
        render :new
      end
    end

    def edit 
      @note = Note.find(params[:id])
    end

    def update
      @note = Note.find(params[:id])
      if @note.update(note_params)
        @note.save
        redirect_to note_path
      else
        render :edit
      end
    end

    def destroy
      @note = Note.find(params[:id])
      @note.destroy
      redirect_to notes_path
    end

    private
    def note_params
      params.require(:note).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/homes/top.html.erb
<div class="container">
    <div class="jumbotron mt-5 text-center">
        <h1 class="display-4">NotesApp</h1>
        <hr class="my-4">
        <p class="lead">
            <div>
            <%= link_to "Noteの一覧", notes_path, class: "btn btn-outline-info" %>
            <%= link_to "Noteの作成", new_note_path, class: "btn btn-outline-secondary" %>
            <%= link_to "会員登録", "#", class: "btn btn-outline-primary" %>

            </div>
        </p>
        <p class="lead">
        <%= link_to 'Start', notes_path, class: 'btn btn-outline-success btn-lg' %>
        </p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <title>NotesApp</title>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- BootstrapのCDNからCSSファイルを読み込み -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
    <div class="navbar-brand">NotesApp</div>
    <div>
    <%= link_to "Noteの一覧", notes_path, class: "btn btn-outline-info" %>
    <%= link_to "Noteの作成", new_note_path, class: "btn btn-outline-secondary" %>
    <%= link_to "会員登録", "#", class: "btn btn-outline-primary" %>

    </div>
    </nav>
    <%= yield %>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/notes/edit.html.erb
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h1 class="text-center mb-4">Create New Note</h1>
        <%= form_with(model: @note, local: true) do |form| %>
            <div class="form-group">
            <%= form.label :title, class: 'font-weight-bold' %>
            <%= form.text_field :title, class: 'form-control' %>
            </div>
            <div class="form-group">
            <%= form.label :body, class: 'font-weight-bold' %>
            <%= form.text_area :body, class: 'form-control', rows: 10 %>
            </div>
            <%= form.submit "ノートを編集する", class: 'btn btn-primary btn-block' %>
        <% end %>
        </div>
    </div>
</div>

app/views/notes/index.html.erb
<div class="container mt-5">
    <h1 class="text-center mb-4">Notes</h1>
    <table class="table table-bordered">
        <thead class="thead-light">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @notes.each do |note| %>
            <tr>
            <td><%= note.id %></td>
            <td><%= note.title %></td>
            <td>
                <%= link_to '詳細', note_path(note), class: 'btn btn-primary' %>
                <%= link_to '編集', edit_note_path(note), class: 'btn btn-secondary' %>
                <%= link_to '削除', note_path(note), data: { turbo_method: :delete ,confirm: '本当に削除しますか？' }, class: 'btn btn-danger'%>
            </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/notes/new.html.erb
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h1 class="text-center mb-4">Create New Note</h1>
        <%= form_with(model: @note, local: true) do |form| %>
            <div class="form-group">
            <%= form.label :title, class: 'font-weight-bold' %>
            <%= form.text_field :title, class: 'form-control' %>
            </div>
            <div class="form-group">
            <%= form.label :body, class: 'font-weight-bold' %>
            <%= form.text_area :body, class: 'form-control', rows: 10 %>
            </div>
            <%= form.submit "ノートを作成する", class: 'btn btn-primary btn-block' %>
        <% end %>
        </div>
    </div>
</div>

app/views/notes/show.html.erb
<div class="container mt-5">
    <h1 class="text-center mb-4">Note #<%= @note.id %></h1>
    <div class="card">
        <div class="card-header">
            <h2><%= @note.title %></h2>
        </div>
        <div class="card-body">
            <p class="card-text"><%= @note.body %></p>
        </div>
        <div class="card-footer text-right">
            <div class="btn-group">
                <%= link_to '戻る', notes_path, class: 'btn btn-primary mr-2' %>
                <%= link_to '編集', edit_note_path(@note), class: 'btn btn-secondary mr-2' %>
                <%= link_to '削除', note_path(@note), data: { turbo_method: :delete ,confirm: '本当に削除しますか？' }, class: 'btn btn-danger mr-2' %>
            </div>
        </div>
    </div>
</div>